"""나라별 **대표 항구·공항** — 수출 화물이 실제로 가는 관문 순서.

전 국가 검사에서 외국 항구·공항의 맨 위가 "이름이 A로 시작하는 곳"이었습니다(쿠웨이트 첫 항구가 카타르 수도처럼 보이는
Doha, 남아공이 Mossel Bay, 케냐가 Lamu, 나이지리아가 해상 유전 Agbami·Akpo, 아이슬란드가 Akureyri 공항). 원자료에는
공항 순위가 거의 없어(1,015곳이 기본값 50) 정렬 근거가 없었습니다.

여기는 **손으로 고른 목록**입니다 — 나라당 대표 관문 몇 곳을 앞에서부터. 목록에 없는 곳은 기존 정렬(직항 여부 ·
항구 규모 · 이름)을 따르고, 목록에 있는 곳은 항상 그 앞에 옵니다. 자료에 없는 코드는 조용히 건너뜁니다.
고칠 때는 이 파일 한 곳만 고치고, tests/test_primary_gateways.py 가 코드 오타를 잡습니다.
"""

from __future__ import annotations

# {국가코드: (UN/LOCODE, …)} — 컨테이너·일반화물 관문 순서. 이 서비스의 위치 자료(+ data/build_extras.py 가 더한 항구)에
# **있는 코드만** 둡니다.
PORTS: dict[str, tuple[str, ...]] = {
    "AE": ('AEJEA', 'AEDXB', 'AESHJ', 'AEAUH'),
    "AO": ('AOLAD',),
    "AR": ('ARBUE',),
    "AU": ('AUSYD', 'AUMEL', 'AUBNE', 'AUFRE'),
    "BD": ('BDCGP',),
    "BE": ('BEANR', 'BEZEE'),
    "BG": ('BGVAR',),
    "BH": ('BHBAH', 'BHKBS'),
    "BR": ('BRSSZ', 'BRPNG', 'BRITJ', 'BRRIO', 'BRSSA'),
    "CA": ('CAVAN', 'CAMTR', 'CAPRR', 'CAHAL'),
    "CI": ('CIABJ',),
    "CL": ('CLVAP', 'CLSAI'),
    "CM": ('CMDLA',),
    "CN": ('CNSGH', 'CNNBO', 'CNSNZ', 'CNQIN', 'CNTXG', 'CNNSA', 'CNXAM', 'CNDAL', 'CNGGZ', 'CNSHG', 'CNNBG', 'CNYTN', 'CNSHK', 'CNCWN', 'CNXMG'),
    "CO": ('COCTG', 'COBUN'),
    "DE": ('DEHAM', 'DEBRV'),
    "DJ": ('DJJIB',),
    "DK": ('DKAAR',),
    "DZ": ('DZALG', 'DZORN'),
    "EC": ('ECGYE',),
    "EG": ('EGPSD', 'EGALY', 'EGDAM', 'EGSUZ'),
    "ES": ('ESVLC', 'ESALG', 'ESBCN'),
    "FI": ('FIHEL',),
    "FR": ('FRLEH', 'FRMRS', 'FRFOS'),
    "GB": ('GBFXT', 'GBLGP', 'GBSOU', 'GBLON'),
    "GE": ('GEPTI', 'GEBUS'),
    "GH": ('GHTEM',),
    "GR": ('GRPIR', 'GRSKG'),
    "HK": ('HKHKG',),
    "ID": ('IDJKT', 'IDSUB', 'IDSRG'),
    "IL": ('ILHFA', 'ILASH'),
    "IN": ('INNSA', 'INMUN', 'INMAA', 'INCCU', 'INVTZ', 'INTUT'),
    "IQ": ('IQUQR', 'IQBSR'),
    "IR": ('IRBND', 'IRBUZ'),
    "IT": ('ITGOA', 'ITSPE', 'ITGIT', 'ITNAP'),
    "JO": ('JOAQJ',),
    "JP": ('JPYOK', 'JPTYO', 'JPNGO', 'JPUKB', 'JPOSA', 'JPHKT'),
    "KE": ('KEMBA',),
    "KH": ('KHKOS',),
    "KW": ('KWSWK', 'KWKWI', 'KWSAA'),
    "LB": ('LBBEY',),
    "LK": ('LKCMB',),
    "MA": ('MAPTM', 'MACAS'),
    "MM": ('MMRGN',),
    "MX": ('MXZLO', 'MXLZC', 'MXVER', 'MXESE'),
    "MY": ('MYPKG', 'MYTPP', 'MYPGU'),
    "MZ": ('MZMPM', 'MZBEW'),
    "NG": ('NGAPP', 'NGLOS', 'NGTIN'),
    "NL": ('NLRTM', 'NLAMS'),
    "NO": ('NOOSL',),
    "NZ": ('NZAKL', 'NZTRG', 'NZLYT'),
    "OM": ('OMSLL', 'OMSOH', 'OMSTQ'),
    "PA": ('PACTB', 'PABLB'),
    "PE": ('PECLL',),
    "PH": ('PHMNL', 'PHCEB'),
    "PK": ('PKKHI', 'PKBQM'),
    "PL": ('PLGDN', 'PLGDY'),
    "PT": ('PTLEI', 'PTSIE'),
    "QA": ('QAHMD', 'QADOH'),
    "RO": ('ROCND',),
    "RU": ('RUVVO', 'RULED', 'RUNVS', 'RUVYP'),
    "SA": ('SAJED', 'SADMM'),
    "SE": ('SEGOT',),
    "SG": ('SGSIN',),
    "SN": ('SNDKR',),
    "TH": ('THLCH', 'THBKK'),
    "TN": ('TNRDS',),
    "TR": ('TRAMR', 'TRMER', 'TRIZM', 'TRGEB'),
    "TW": ('TWKHH', 'TWKEL', 'TWTPE'),
    "TZ": ('TZDAR',),
    "UA": ('UAODS', 'UAILK'),
    "US": ('USLAX', 'USLGB', 'USNYC', 'USSAV', 'USSEA', 'USHOU', 'USOAK', 'USCHS', 'USMIA', 'USORF'),
    "UY": ('UYMVD',),
    "VN": ('VNSGN', 'VNCMT', 'VNHPH', 'VNDAD', 'VNVUT'),
    "ZA": ('ZADUR', 'ZACPT', 'ZAPLZ', 'ZARCB'),
}

# {국가코드: (IATA, …)} — 국제 화물이 실제로 가는 공항 순서
AIRPORTS: dict[str, tuple[str, ...]] = {
    "US": ('LAX', 'JFK', 'ORD', 'ATL', 'MIA', 'SFO', 'DFW', 'SEA', 'IAH', 'ANC'),
    "CA": ('YYZ', 'YVR', 'YUL'),
    "MX": ('MEX', 'GDL', 'MTY'),
    "BR": ('GRU', 'VCP', 'GIG'),
    "AR": ('EZE',),
    "CL": ('SCL',),
    "CO": ('BOG', 'MDE'),
    "PE": ('LIM',),
    "EC": ('UIO', 'GYE'),
    "VE": ('CCS',),
    "PA": ('PTY',),
    "UY": ('MVD',),
    "BO": ('VVI', 'LPB'),
    "PY": ('ASU',),
    "GB": ('LHR', 'MAN', 'STN', 'EMA'),
    "DE": ('FRA', 'MUC', 'LEJ', 'CGN', 'HAM'),
    "NL": ('AMS',),
    "BE": ('BRU', 'LGG'),
    "FR": ('CDG', 'LYS', 'MRS'),
    "ES": ('MAD', 'BCN'),
    "IT": ('MXP', 'FCO', 'BGY', 'LIN'),
    "PT": ('LIS',),
    "PL": ('WAW', 'KTW'),
    "TR": ('IST', 'SAW'),
    "RU": ('SVO', 'DME', 'VKO', 'LED'),
    "SE": ('ARN',),
    "DK": ('CPH',),
    "NO": ('OSL',),
    "FI": ('HEL',),
    "AT": ('VIE',),
    "CH": ('ZRH', 'GVA'),
    "IE": ('DUB',),
    "CZ": ('PRG',),
    "HU": ('BUD',),
    "GR": ('ATH',),
    "RO": ('OTP',),
    "IS": ('KEF',),
    "GE": ('TBS',),
    "AM": ('EVN',),
    "AZ": ('GYD',),
    "KZ": ('ALA', 'NQZ'),
    "UZ": ('TAS',),
    "KG": ('BSZ',),
    "TJ": ('DYU',),
    "MN": ('UBN',),
    "JP": ('NRT', 'KIX', 'HND', 'NGO', 'FUK'),
    "CN": ('PVG', 'CAN', 'PEK', 'SZX', 'CTU', 'TAO'),
    "HK": ('HKG',),
    "TW": ('TPE',),
    "VN": ('SGN', 'HAN'),
    "TH": ('BKK',),
    "MY": ('KUL', 'PEN'),
    "SG": ('SIN',),
    "ID": ('CGK', 'SUB'),
    "PH": ('MNL', 'CEB'),
    "KH": ('SAI',),
    "MM": ('RGN',),
    "LA": ('VTE',),
    "BN": ('BWN',),
    "IN": ('DEL', 'BOM', 'MAA', 'BLR', 'HYD', 'CCU'),
    "PK": ('KHI', 'LHE', 'ISB'),
    "BD": ('DAC',),
    "LK": ('CMB',),
    "NP": ('KTM',),
    "MV": ('MLE',),
    "AE": ('DXB', 'AUH', 'SHJ', 'DWC'),
    "SA": ('RUH', 'JED', 'DMM'),
    "QA": ('DOH',),
    "KW": ('KWI',),
    "BH": ('BAH',),
    "OM": ('MCT',),
    "IL": ('TLV',),
    "JO": ('AMM',),
    "LB": ('BEY',),
    "IQ": ('BGW', 'BSR', 'EBL'),
    "IR": ('IKA', 'THR'),
    "EG": ('CAI',),
    "MA": ('CMN',),
    "DZ": ('ALG',),
    "TN": ('TUN',),
    "NG": ('LOS', 'ABV'),
    "GH": ('ACC',),
    "CI": ('ABJ',),
    "SN": ('DSS',),
    "KE": ('NBO',),
    "ET": ('ADD',),
    "TZ": ('DAR',),
    "UG": ('EBB',),
    "ZA": ('JNB', 'CPT', 'DUR'),
    "MZ": ('MPM',),
    "AO": ('LAD',),
    "ZM": ('LUN',),
    "ZW": ('HRE',),
    "MU": ('MRU',),
    "AU": ('SYD', 'MEL', 'BNE', 'PER'),
    "NZ": ('AKL', 'CHC'),
    "PG": ('POM',),
    "FJ": ('NAN',),
    "TT": ('POS',),
    "DO": ('SDQ',),
    "CR": ('SJO',),
    "GT": ('GUA',),
    "JM": ('KIN',),
    "PR": ('SJU',),
}


def port_rank(country_code: str, code: str) -> int:
    """대표 항구 순서(0부터). 목록에 없으면 99."""

    order = PORTS.get((country_code or "").upper(), ())
    return order.index(code) if code in order else 99


def airport_rank(country_code: str, code: str) -> int:
    order = AIRPORTS.get((country_code or "").upper(), ())
    return order.index(code) if code in order else 99


def is_primary(country_code: str, code: str) -> bool:
    return port_rank(country_code, code) < 99 or airport_rank(country_code, code) < 99
